import {Context} from "telegraf";
import {mockTelegram} from "./mockTelegram";
import {mockUpdate} from "./mockUpdate";

export const mockContext: Context = {
  addStickerToSet: jest.fn(),
  answerCbQuery: jest.fn(),
  answerGameQuery: jest.fn(),
  answerInlineQuery: jest.fn(),
  answerPreCheckoutQuery: jest.fn(),
  answerShippingQuery: jest.fn(),
  createNewStickerSet: jest.fn(),
  deleteChatPhoto: jest.fn(),
  deleteMessage: jest.fn(),
  deleteStickerFromSet: jest.fn(),
  editMessageCaption: jest.fn(),
  editMessageLiveLocation: jest.fn(),
  editMessageMedia: jest.fn(),
  editMessageReplyMarkup: jest.fn(),
  editMessageText: jest.fn(),
  exportChatInviteLink: jest.fn(),
  getChat: jest.fn(),
  getChatAdministrators: jest.fn(),
  getChatMember: jest.fn(),
  getChatMembersCount: jest.fn(),
  getStickerSet: jest.fn(),
  kickChatMember: jest.fn(),
  leaveChat: jest.fn(),
  pinChatMessage: jest.fn(),
  promoteChatMember: jest.fn(),
  reply: jest.fn(),
  replyWithAudio: jest.fn(),
  replyWithChatAction: jest.fn(),
  replyWithDice: jest.fn(),
  replyWithDocument: jest.fn(),
  replyWithGame: jest.fn(),
  replyWithHTML: jest.fn(),
  replyWithInvoice: jest.fn(),
  replyWithLocation: jest.fn(),
  replyWithMarkdown: jest.fn(),
  replyWithMediaGroup: jest.fn(),
  replyWithPhoto: jest.fn(),
  replyWithPoll: jest.fn(),
  replyWithQuiz: jest.fn(),
  replyWithSticker: jest.fn(),
  replyWithVideo: jest.fn(),
  replyWithVoice: jest.fn(),
  restrictChatMember: jest.fn(),
  setChatTitle: jest.fn(),
  setStickerPositionInSet: jest.fn(),
  stopMessageLiveLocation: jest.fn(),
  stopPoll: jest.fn(),
  unbanChatMember: jest.fn(),
  unpinChatMessage: jest.fn(),
  uploadStickerFile: jest.fn(),
  telegram: mockTelegram,
  tg: mockTelegram,
  update: mockUpdate,
  updateSubTypes: ["text"],
  updateType: "message"
};

export default mockContext;
