plugins:
  eslint:
    enabled: true
    config: .eslint.yml
exclude_patterns:
- ".github/"
- ".vscode/"
- "docs/"
- "patches/"
- "*.md"
- "LICENSE"
- "package.json"
- "yarn.lock"
- "**/.gitignore"
- "**/__fixtures__/*"
