plugins:
  fixme:
    enabled: true
  editorconfig:
    enabled: true
  eslint:
    enabled: false
    config: .eslint.yml
exclude_patterns:
- ".github/"
- ".vscode/"
- "docs/"
- "patches/"
- "*.md"
- "LICENSE"
- "package.json"
- "yarn.lock"
- "**/.gitignore"
- "**/__fixtures__/*"
- "**/__mocks__/*"
- "**/*.spec.ts"
