plugins:
  fixme:
    enabled: true
  editorconfig:
    enabled: true
  eslint:
    enabled: false
    config: .eslint.yml
exclude_patterns:
- ".github/"
- ".vscode/"
- ".dockerignore"
- ".editorconfig"
- ".eslint.yml"
- ".Dockerfile"
- "Makefile"
- "LICENSE"
- "package.json"
- "yarn.lock"
- "default.tmpl"
- "tsconfig.json"
- "typedoc.json"
- "tsconfig.*.json"
- "*.md"
- "**/.gitignore"
- "**/*.spec.ts"
- "**/*.d.ts"
- "scripts/"
- "docs/"
- "patches/"
- "**/__fixtures__/*"
- "**/__mocks__/*"
