name: DockerHub

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: ghe-actions/dockerfile-validator@master
        with:
          lint: 'dockerlint'
          dockerlabelvalidate: 'yes'

      - name: Publish image on Docker Hub
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          build_args: BUILDKIT_INLINE_CACHE=1
          tags: latest
          cache_froms: ${{ github.repository }}:latest

      - name: Update Docker Hub readme and description
        uses: meeDamian/sync-readme@v1.0.6
        with:
          pass: ${{ secrets.DOCKER_PASSWORD }}
          description: true
